language: python
sudo: false
cache: pip
python:
- "3.5"  # Django 1.8 does not officially support 3.6
- "2.7"
env:
- REQ="Django>=1.8,<1.9"
install:
- pip install -U pip wheel
- pip install $REQ -r requirements.txt
- python setup.py install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
