language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.6"
env:
  - REQ="Django>=1.9"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -q $REQ -r requirements.txt --use-mirrors
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
