language: python
sudo: false
cache: pip
python:
  - "2.7"
  - "3.4"
env:
  - REQ="Django>=1.8,<1.9"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U setuptools wheel pip
  - pip install -q $REQ simplejson==3.8.0 openpyxl==2.2.6 reportlab==3.2.0 pdfdocument==3.1 django-countries==3.3
  - python setup.py -q install
# command to run tests, e.g. python setup.py test
script: "cd tests && ./manage.py test testapp"
